#!/bin/sh 

rel=$1
shift
files=$*

if [ "${files}" != "" ]; then
	echo "Using supplied file list ${files}"
else
	if [ ! -f '.setrel_inventory' ]; then
		echo "No inventory found to fix versions on, exiting."
		exit 1
	fi
	files=`cat .setrel_inventory`
fi

if [ -n "`git status --porcelain`" ]; then
	echo "Working directory not ready, you shouldn't screw with versions"
	git status --porcelain
	echo "Do it anyway?"
	read ans
	if [ "${ans}" != "y" ]; then
		exit 1
	fi
fi


for file in ${files}; do
	echo "Version switch on ${file}"
	# Set up right permissions
	cp -p ${file} ${file}.ver
	# fix the release tag
	cat $file | perl -pe "s/\\\$Release: .*?\\$/\\\$Release: ${rel}\\$/" >${file}.ver
	# move changes in to place
	mv ${file}.ver ${file}
done
